### ISSUE TITLE
Server'ı nasıl değiştirebilirim ?

### ISSUE THREAD

**Issue by bussrakrkmz** [HaydiKodlayalim/spring-examples#33]
Merhabalar,

Spring projenizi localhost ile değil de manuel olarak gireceğim bir server ile çalıştırmam mümkün mü? Eğer mümkünse nasıl yapabilirim?
Örneğin http://localhost:8080 yerine http://springwebservistest gibi bir kullanım 

Teşekkürler,

**Comment by temelt** [comment]
Merhaba 
Bunun icin /etc/hosts dosyasina 

127.0.0.1 http://springwebservistest 

bu sekilde bir entry eklemen yeterli

**Comment by bussrakrkmz** [comment]
Bu tüm sistemin localhost adresini değiştirmez mi ? Ben sadece spring projesinin herkes tarafından erişilebilir olmasını istiyorum.
